name: 'GitHub Status Embed for Discord'
description: 'Send a custom GitHub Status Embed to a Discord Webhook'

inputs:
  name:  # id of input
    description: 'Who to greet'
    required: true
    default: 'Sebastiaan'

outputs:
  status:
    description: 'The status response for the webhook request'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.name }}
